language: node_js
node_js:
- '6'

# ssh_known_hosts addon currently does not work with env var
# see https://github.com/travis-ci/travis-ci/issues/7043
# addons:
#   ssh_known_hosts: $deploy_host

before_script:
  - echo -e "Host $deploy_host\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

script:
  - openssl aes-256-cbc -K $encrypted_539d231ab808_key -iv $encrypted_539d231ab808_iv -in .travis/muffin.enc -out .travis/muffin -d
  - chmod 600 .travis/muffin
  - eval "$(ssh-agent -s)" # start the ssh agent
  - ssh-add .travis/muffin
  - git remote add deploy $deploy_user@$deploy_host:$deploy_uri
  - git push deploy master
